### ISSUE TITLE
No menu bar on first launch

### ISSUE THREAD

**Issue by DavidPhillipOster** [markydoodled/Note.it#6]
## To reproduce

Happens on first launch only. 
Big Sur 11.3 (Intel)

On first launch, Note.it brings up the open file dialog. If you hit the 'new document' button, you get a menu bar with just the apple menu, none of the menus for the app itself. And there's a stack trace in Xcode showing that it threw an exception building the menu bar.

On a second launch, everything is fine.

## Also

I've never used the cocoapods KeyboardShortcuts or preferences before. It's possible they write some global preferences that keep you from seeing this bug.

## Workround

Click 'Quit' from the contextual menu on the Note.it dock icon. Note that nothing happens.
Click 'Quit' again from the contextual menu on the Note.it dock icon. App quits normally.
Normal menu bar appears after that.

## To reproduce the error
with the app not running, in ~/Library/Containers delete the directory with the app's bundle ID.

## Attached file: 
1 stack trace from Xcode's console window
[exception.txt](https://github.com/markydoodled/Note.it/files/6416275/exception.txt)

2 screenshot showing no menu bar
![no Menu Bar](https://user-images.githubusercontent.com/5148308/116905661-22413200-abf4-11eb-89e9-61395a6ad7a7.png)

**Comment by markydoodled** [comment]
The error provided is the same I got when developing the new menu bar. If you are using the release version everything should be fine. However, if you are using the source code directly and modify the app delegate and try to compile, this error will happen. I'm not sure what causes this, but I am sure that it's something to do with how NSMenu is setup. Make sure you have both the KeyboardShortcuts and Preferences swift packages too. To get around this in code, comment out the two lines in the image below, recompile and then uncomment them, and recompile again. 

![Screenshot 2021-05-03 at 18 04 47](https://user-images.githubusercontent.com/68232529/116907948-3740b400-ac3a-11eb-8465-76db3bbe0100.png)

I hope this helps people who have this issue.

**Comment by DavidPhillipOster** [comment]
That doesn't actually iix the problem. It just requires individual programmers to discover it and paper over it. Here's a change that actually fixes the problem:

    func applicationDidFinishLaunching(_ notification: Notification) {
      DispatchQueue.main.async(){
        let menu = ContentView.AppMenu()
        NSApp.mainMenu = menu
      }
    }

**Comment by markydoodled** [comment]
Thanks for that code. I wasn't even aware that you could use asynchronous loading on that type of code. I'll implement that change soon.
